Description: This will define S3 bucket(s) and DynamoDB tables necessary for the bot to function.

Resources:
  MusicBucket:
    Type: AWS::S3::Bucket
    DeltionPolicy: Retain
    Properties:
      BucketName: dj-rawk-music